env:
    MANIFEST: https://gitlab.e.foundation/e/os/android.git -b v1-r --depth=1 --no-repo-verify
    DEVICE: RMX2020
    OEM: realme
    DT_LINK: https://github.com/CyanFinchLing/device_realme_RMX2020.git -b lineage-18.1-rmui1
    DT_PATH: device/$OEM/$DEVICE
    VT_LINK: https://github.com/Realme-G70-Series/vendor_realme_RMX2020.git
    VT_PATH: vendor/$OEM/$DEVICE
    KT_LINK: https://github.com/sarthakroy2002/kernel_realme_rmx2020.git -b Q
    PLATFORM: mt6768
    KT_PATH: kernel/$OEM/$DEVICE
    TARGET: bacon
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: eos_${DEVICE}-userdebug
    OUTPUT: EOS*.zip

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G
        
  
  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/work
      - cd ~/work
      - repo init -u $MANIFEST
      - repo sync
      - git clone --depth=1 $DT_LINK $DT_PATH
      - git clone --depth=1 $VT_LINK $VT_PATH
      - git clone --depth=1 $KT_LINK $KT_PATH
      - git clone --depth=1 https://github.com/Realme-G70-Series/android_packages_apps_RealmeParts -b lineage-18.1 packages/apps/RealmeParts
      - git clone --depth=1 https://github.com/Realme-G70-Series/android_packages_apps_RealmeDirac -b lineage-18.1 packages/apps/RealmeDirac
      - rm -rf external/selinux
      - git clone --depth=1 https://github.com/Los-FE/android_external_selinux -b lineage-18.1 external/selinux
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - $EXTRA_CMD
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 50G
      - . build/envsetup.sh
      - lunch eos_RMX2020-userdebug
      - mka bacon
     
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~/work
      - cd out/target/product/"$DEVICE"
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file $(echo $OUTPUT) https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
        
